window.angular.module('UIApp')
.config(['$translateProvider', function( $translateProvider ) {

  $translateProvider.translations('es', {
    GREETING: '¡Hola Mundo!',
    LANGUAGE: 'Idioma',
    ENGLISH: 'Inglés',
    SPANISH: 'Español',
    GERMAN: 'Alemán',
    ITALIAN: 'Italiano',
    BUILD_SETUP: 'CONFIGURA TU PRODUCTO',
    FRENCH: 'Frances',
    SEARCH: 'Buscar',
    OLD_PASSWORD: 'Contraseña actual',
    PASSWORD: 'Nueva Contraseña',
    CONFIRM_PASSWORD: 'Confirme Contraseña nueva',
    SELECT_CSV: 'Importar CSV',
    PREVIOUS: 'Anterior',
    FINISH: 'Finalizar',
    NEXT: 'Siguiente',
    WIZARD_GUIDE: 'Este paso a paso te guiará en la configuración del producto.',
    INCREASE: 'Añadir',
    DECREASE: 'Quitar',
    EDIT: 'Editar',
    DELETE: 'Eliminar',
    FROM: 'Desde',
    TO: 'Hacia',
    CLEAN: 'Limpiar',
    ITEM_TO_ISSUE: 'Items para prestar',
    // LOCATION: 'Ubicación',
    // POSITION: 'Posición',
    PRODUCT: 'Producto/SKU',
    PRODUCT_SETUP: 'Configuración de Producto',
    PRODUCT_WIZARD: 'Asistente de Producto',
    ITEMS: 'Productos',
    ITEM: 'Producto',
    QUANTITY: 'Cantidad',
    INVENTORY_MANAGEMENT: 'Manejo de Inventario',
    MANUAL: 'Manual',
    HELP: 'Ayuda',
    ABOUT: 'Acerca',
    STATUS: {
      ACTIVE: 'Activo',
      INACTIVE: 'Inactivo',
      DISABLED: 'Desabilitado',
      PENDING: 'Pendiente'
    },
    ACTIONS: {
      NEW: 'Nuevo',
      SEND: 'Enviar',
      REMOVE: 'Eliminar',
      CANCEL: 'Cancelar',
      UPDATE: 'Actializar',
      SEARCH: 'Buscar',
      SERIALIZE: 'Crear unidad serializada'
    },
    PRODUCTS: {
      PRODUCT: 'Producto',
      NEW_PRODUCT: 'Nuevo producto',
      PROPERTIES: 'Propiedades',
      NEW: 'Nuevo',
      CANCEL: 'Cancelar',
      SEND: 'Enviar',
      DESTROY: 'Borrar',
      UPDATE: 'Actualizar',
      EDIT_PROD: 'Editando producto',
      QRCODE: 'Código QR',
      BARCODE: 'Código de Barras',
      SKU: 'SKU',
      SHORT_DESC: 'Descripción corta',
      LONG_DESC: 'Descripcion larga',
      ALT_DESC: 'Descripción alternativa',
      FACT_NUM: 'Número de fábrica',
      CUST_NUM: 'Numero del cliente',
      ALT_NUM: 'Número alternativo',
      SEC_ALT_NUM: 'Número alternativo secundario',
      MANUFACTURE: 'Fábricante',
      CROSS_NUM: 'Número cruzado',
      SUPPLIER: 'Proveedor',
      SUPP_NUM: 'Número del provoeedor',
      PRICE: 'Precio',
      CATEGORY: 'Categoría',
      COLOR: 'Color',
      SERIAL: 'Serial',
      COMP_SIZE: 'Tamaño del compartimento',
      DIMENSIONS: 'Dimensiones',
      STATUS: 'Estado',
      EMPTY: 'No hay productos',
      HELP_SHORT_DESC: 'Una corta description para este producto.',
      HELP_LONG_DESC: 'Una descripción completa para este producto.',
      HELP_ALT_DESC: 'Una descripción alterna para este producto.',
      TO_RESTOCK: 'Posiciones para surtir',
      SKU_EMPTY: 'Sku no puede estar en blanco',
      BARCODE_EMPTY: 'El codigo de barras no puede estar en blanco',
      SHORT_DESC_EMPTY: 'Ingrese una descripción corta del producto',
      DELETE_FAIL: 'El producto no se puede eliminar'
    },
    INVENTORY: {
      ISSUE: 'issue',
      RESTOCK: 'Surtir',
      RECLAIM: 'Reclamar',
      ASSIGN: 'Asignar',
      MOVE: {
        MOVE: 'Mover',
        CAN_NOT_EMPTY_POS: "¡No puedes escoger una posición vacía!",
        CAN_EMPTY_POS: "¡Debes escoger una posición vacía!"
      },
      TRANSFER: 'Transferir',
      ENTER_PRODUCT: 'Ingresar Producto SKU',
      FINISH_TRANSACTION: 'Finalizar Transacción',
      REMOVE: 'Eliminar',
      DEST_SITE: 'Sitio de destino'
    },
    ASSETS: {
      TITLE: 'Activos',
      EMPTY: 'No hay Activos',
      NEW_ASSET: 'Nuevo activo',
      EDIT_ASSET: 'Editando activo',
      PRODUCT: 'Producto',
      CHECK_IN: 'Check in',
      CHECK_OUT: 'Check out',
      LOAN_TIME: 'Tiempo de préstamo (min)',
      LOAN_TIME_H: 'Tiempo de préstamo (hrs)',
      RECHARGEAGLE: 'Recargable',
      RECHARGEAGLE_TIME: 'Tiempo de recarga (min)',
      CALIBRATION: 'Calibración',
      CALIBRATION_TIME: 'Periodo de tiempo para calibración (min)',
      LOCKED_DOWN: 'Bloqueado',
      REASON: 'Rason',
      STATUS: 'Status',
      ITEM_EMPTY: 'Producto no puede estar vacio',
      CALIBRATION_TIME_EMPTY: 'Periodo de tiempo de calibración no puede estar vacio',
      RECHARGEABLE_TIME_EMPTY: 'Tiempo de recarga no puede estar vacio'
    },
    COMPANY: {
      MENU: 'Compañía',
      COMPANY: 'Administración de Compañías',
      ADD: 'Añadir Compañía',
      DELETE: 'Eliminar Compañía',
      SAVE: 'Guardar',
      COMPANY_NAME: 'Nombre de la Compañía',
      LOGO: 'Logo',
      MESSAGE: 'Mensaje',
      DEFAULT_LANG: 'Lenguage por Defecto',
      ADDRESS: 'Dirección',
      COMPANY_TYPE: 'Tipo de Compañía',
      PHONE: 'Telefono',
      LOGGING: 'Log de Transacciones',
      SEARCH: 'Buscar Compañía por nombre',
      CANCEL: 'Cancelar',
      EDIT: 'Editar Compañía',
      NAME_EMPTY: 'El nombre de la Compañía no puede estar en blanco',
      DEFAULT_LANG_EMPTY: 'El lenguage por defecto de la Compañía debe ser seleccionado',
      TYPE_EMPTY: 'El tipo de Compañía debe ser seleccionado'
    },
    SITE: {
      MENU: 'Sitio',
      SITE: 'Administración de Sitios',
      ADD: 'Añadir',
      EDIT: 'Editar',
      CANCEL: 'Cancelar',
      DELETE: 'Eliminar',
      NEW: 'Nuevo Sitio',
      SAVE: 'Guardar',
      NAME: 'Nombre',
      ADDRESS: 'Dirección',
      SEARCH: 'buscar sitio por nombre',
      NAME_EMPTY: 'El nombre del site no puede estar en blanco',
      ADDRESS_EMPTY: 'La dirección del site no puede estar en blanco'
    },
    LOCATION: {
      MENU: 'Ubicación',
      LOCATION_MANAGEMENT: 'Administración de Ubicaciones',
      LOCATION: 'Ubicación',
      ADD: 'Añadir',
      EDIT: 'Editar',
      CANCEL: 'Cancelar',
      DELETE: 'Eliminar',
      NEW: 'Nueva Ubicación',
      SAVE: 'Guardar',
      SITE: 'Sitio',
      NAME: 'Nombre',
      NAME_EMPTY: 'El nombre de la ubicación no puede estar en blanco',
      SITE_NAME_EMPTY: 'El sitio debe ser seleccionado',
      SEARCH: 'buscar locación por nombre'
    },
    POSITION: {
      MENU: 'Posición',
      POSITION: 'Posición',
      POSITION_MANAGEMENT: 'Administración de Posiciones',
      ADD: 'Añadir',
      EDIT: 'Editar',
      CANCEL: 'Cancelar',
      DELETE: 'Eliminar',
      NEW: 'Nueva Posición',
      SAVE: 'Guardar',
      SITE: 'Sitio',
      LOCATION: 'Ubicación',
      NAME: 'Nombre',
      SHELF: 'Shelf',
      BIN: 'Bin',
      CUR_QTY: 'Cantidad Actual',
      MIN_QTY: 'Cantidad Mínima',
      MAX_QTY: 'Cantidad Máxima',
      CRITICAL_QTY: 'Cantidad Crítica',
      NAME_EMPTY:'El nombre de la posición no puede estar en blanco',
      SITE_EMPTY: 'El sitio debe ser seleccionado',
      LOCATION_EMPTY: 'La ubicación debe ser seleccionada',
      ITEM_EMPTY: 'El producto debe ser seleccionado',
      SHELF_EMPTY: 'Shelf no puede estar en blanco',
      BIN_EMPTY: 'Bin no puede estar en blanco',
      MIN_QTY_EMPTY: 'La cantidad mínima no puede estar en blanco',
      MAX_QTY_EMPTY: 'La cantidad máxima no puede estar en blanco',
      MAX_GREATER: 'La cantidad máxima debe ser mayor que la cantidad mínima',
      CRITICAL_QTY_EMPTY: 'La cantidad crítica no puede estar en blanco',
      CRITICAL_QTY_LESS: 'La cantidad crítica deber ser menor o igual que la catidad mínima',
      ITEM: 'Producto',
      SEARCH: 'buscar Posición por nombre'
    },
    STORAGE_HIERARCHY: {
      MENU: 'Almacenamiento',
      SUB_MENU: 'Jerarquía de Almacenamiento',
      STORAGE_HIERARCHY: 'Jerarquía de Almacenamiento'
    },
    USER: {
      USERS: 'Usuarios',
      USER: 'Registro de usuario',
      SAVE: 'Guardar',
      NAME: 'Nombre',
      LAST_NAME: 'Apellido',
      PHONE: 'Teléfono',
      CELL_PHONE: 'Celular',
      EMAIL: 'Email',
      PASSWORD: 'Contraseña',
      LANGUAGE: 'Idioma',
      EDIT: 'Editar',
      CANCEL: 'Cancelar',
      DELETE: 'Eliminar',
      ROLE: 'Rol',
      NEW: 'Nuevo usuario',
      LIST: 'Lista',
      EDITION: 'Edición',
      SEARCH: 'Buscar usuario...',
      WELCOME: 'Bienvenido',
      SETTINGS: 'Configuración',
      CONTACT_SUPPORT: 'Soporte',
      LOG_OUT: 'Salir',
      SIGN_IN: 'Ingresar',
      SIGN_UP: 'Registrarse',
      USERROLE: 'Usuario',
      ADMINROLE: 'Administrador',
      NAME_EMPTY: 'El Nombre de usuario no puede estar en blanco',
      EMAIL_EMPTY: 'El email del usuario no puede estar en blanco',
      LANGUAGE_EMPTY: 'El idioma del usuario se debe seleccionar',
      PASSWORD_EMPTY: 'La contraseña no puede estar en blanco',
      PASSWORD_SHORT: 'La contraseña es demasiado corto, debe contener al menos ocho caracteres',
      CHECKBOX_ROLE: 'Es Administrador?'
    },
    REPORT: {
      GENERAL_REPORTING: 'Reporte General',
      RESTOCK_MANAGEMENT: {
        TITLE: 'Reporte de Abastecimiento',
        NEEDED_QTY: 'Cantidad Mínima Requerida'
      },
      TITLE: 'Reportes',
      ISSUE: {
        NUMBER: 'Número de Novedad',
        TITLE: 'Registro de Novedades',
        USER_EMAIL: 'Usuario',
        USER_NAME: 'Nombre Completo',
        ITEM: 'Item Seleccionado',
        ITEM_SKU: 'Número SKU',
        QUANTITY: 'Cantidad',
        SITE: 'Sede de Novedad',
        LOCATION: 'Localización de Novedad',
        POSITION: 'Estante/Posición',
        DATE: 'Fecha de Novedad',
        FROM: 'Novedades desde',
        TO: 'Novedades Hasta',
        FIND: 'Buscar Novedades'
      },
      CHECKBOOK: {
        TITLE: 'Chequera',
        EVENT_TYPE: 'Tipo de Evento',
        EVENT_DATE: 'Fecha del Evento'
      },
      LACK: {
        TITLE: 'Productos nunca usados',
        HIDE: 'Ocultar detalles',
        SHOW: 'Ver detalles',
        ID: 'Id',
        NAME: 'Nombre',
        NO_ITEMS: 'No hay productos'
      },
      STATS_FOR_VELOCITY: {
        TITLE: 'Estadíticas de Velocidad',
        SKU_NUMBER: 'Número SKU',
        RATE: 'Tasa de Velocidad(Unidades/Dia)',
        FROM: 'Desde',
        TO: 'Hasta',
        LOCATION: 'Location'
      }
    },
    DASHBOARD:{
      SHOW_DETAILS: 'Mostrar más detalles',
      VELOCITY: {
        TITLE: 'Es el mejor promedio del mes'
      },
      RATE: '{{value}}/dia'
    },
    NO_RESULTS: 'No se Encontraron Resultados',
    BACK: 'Regresar a la Página Principal'
  });
}]);
