(function () {

  'use strict';


  window.angular.module('UIApp')
  .config(['$translateProvider', function( $translateProvider ) {

    $translateProvider.translations('fr', {
      GREETING: 'Bonjour Le Monde!',
      LANGUAGE: 'Langue',
      ENGLISH: 'Anglais',
      SPANISH: 'Espagnol',
      GERMAN: 'Allemand',
      ITALIAN: 'Italien',
      FRENCH: 'Français',
      INCREASE: 'augmentation',
      BUILD_SETUP: 'BUILD YOUR PRODUCT SETUP',
      PREVIOUS: 'Previous',
      FINISH: 'Finish',
      NEXT: 'Next',
      WIZARD_GUIDE: 'This wizard will take you throught product configuration.',
      DECREASE: 'diminution',
      OLD_PASSWORD: 'Old Password',
      PASSWORD: 'Password',
      CONFIRM_PASSWORD: 'Confirm new Password',
      SELECT_CSV: 'Import CSV',
      FROM: 'From',
      TO: 'To',
      EDIT: 'Edit',
      DELETE: 'Delete',
      CLEAN: 'Clean',
      ITEM_TO_ISSUE: 'Items to issue',
      SEARCH: 'Articles d\'émettre',
      // LOCATION: 'Location',
      // POSITION: 'Position',
      PRODUCT: 'produit/SKU',
      PRODUCT_SETUP: 'Configuration du Produit',
      PRODUCT_WIZARD: 'Assistant de Produit',
      ITEMS: 'produits',
      ITEM: 'produit',
      INVENTORY_MANAGEMENT: 'Gestion des stocks',
      MANUAL: 'manuel',
      HELP: 'Aidez-Moi',
      ABOUT: 'sur',
      QUANTITY: 'quantité',
      STATUS: {
        ACTIVE: 'actif',
        INACTIVE: 'inactif',
        DISABLED: 'handicapé',
        PENDING: 'en attendant'
      },
      ACTIONS: {
        NEW: 'nouveau',
        SEND: 'envoyer',
        REMOVE: 'supprimer',
        CANCEL: 'annuler',
        UPDATE: 'mettre à jour',
        SEARCH: 'recherche',
        SERIALIZE: 'Créer Unité Serialized'
      },
      PRODUCTS: {
        NEW_PRODUCT: 'Nouveau Produit',
        PROPERTIES: 'propriétés',
        NEW: 'nouveau',
        PRODUCT: 'produit',
        CANCEL: 'annuler',
        SEND: 'envoyer',
        DESTROY: 'détruire',
        UPDATE: 'mettre à jour',
        EDIT_PROD: 'produits d\'édition',
        QRCODE: 'QR Code',
        BARCODE: 'Code-Barres',
        SKU: 'SKU',
        SHORT_DESC: 'brève description',
        LONG_DESC: 'Description longue',
        ALT_DESC: 'autre description',
        FACT_NUM: 'numéro d\'usine',
        CUST_NUM: 'Customer client',
        ALT_NUM: 'Autre numéro',
        SEC_ALT_NUM: 'Autre numéro secondaire',
        MANUFACTURE: 'fabrication',
        CROSS_NUM: 'numéro de la Croix-',
        SUPPLIER: 'fournisseur',
        SUPP_NUM: 'Numéro de fournisseur',
        PRICE: 'prix',
        CATEGORY: 'catégorie',
        COLOR: 'couleur',
        SERIAL: 'en série',
        COMP_SIZE: 'La taille du compartiment',
        DIMENSIONS: 'dimensions',
        STATUS: 'statut',
        EMPTY: 'Il n\'y a pas de produits',
        HELP_SHORT_DESC: 'Courte description pour ce produit',
        HELP_LONG_DESC: 'Description longue pour ce produit',
        HELP_ALT_DESC: 'Description alternative pour ce produit',
        TO_RESTOCK: 'Postes à réapprovisionner',
        SKU_EMPTY: 'Sku ne peut être vide ',
        BARCODE_EMPTY: 'Barcode ne peut être vide ',
        SHORT_DESC_EMPTY: 'Courte description du produit ne peut être vide',
        DELETE_FAIL: 'Produit ne peut pas être supprimé'
      },
      INVENTORY: {
        ISSUE: 'issue',
        RESTOCK: 'réapprovisionner',
        RECLAIM: 'Reclaim',
        ASSIGN: 'assigner',
        MOVE: {
          MOVE: 'Move',
          CAN_NOT_EMPTY_POS: 'You can\'t choose an empty position!',
          CAN_EMPTY_POS: 'You should choose an empty position!'
        },
        TRANSFER: 'Transfer',
        ENTER_PRODUCT: 'Entrez produit SKU',
        FINISH_TRANSACTION: 'Terminer Transaction',
        REMOVE: 'supprimer',
        DEST_SITE: 'Destination site'
      },
      ASSETS: {
        TITLE: 'Actif',
        EMPTY: 'Il ne est pas actif',
        NEW_ASSET: 'Nouvel atout',
        EDIT_ASSET: 'Édition actif',
        PRODUCT: 'Produit',
        CHECK_IN: 'Enregistrement',
        CHECK_OUT: 'Check-out',
        LOAN_TIME: 'Temps de prêt (min)',
        LOAN_TIME_H: 'Temps de prêt (hrs)',
        RECHARGEAGLE: 'Rechargeable',
        RECHARGEAGLE_TIME: 'Temps rechargeable (min)',
        CALIBRATION: 'Étalonnage',
        CALIBRATION_TIME: "Période de temps d'étalonnage (min)",
        LOCKED_DOWN: 'Verrouillé',
        REASON: 'Raison',
        STATUS: 'Rtatut',
        ITEM_EMPTY: 'Produit ne peut être vide',
        CALIBRATION_TIME_EMPTY: 'Période de temps d\'étalonnage ne peut être vide',
        RECHARGEABLE_TIME_EMPTY: 'Temps rechargeable ne peut être vide'
      },
      COMPANY: {
        MENU: 'compagnie',
        COMPANY: 'Gestion de l\'entreprise',
        ADD: 'Ajouter entreprise',
        DELETE: 'effacer entreprise',
        SAVE: 'Enregistrer',
        COMPANY_NAME: 'Nom de l\'entreprise',
        LOGO: 'logo',
        MESSAGE: 'message',
        DEFAULT_LANG: 'Langue par défaut',
        ADDRESS: 'adresse',
        COMPANY_TYPE: 'Type d\'entreprise',
        PHONE: 'téléphone',
        LOGGING: 'enregistrement',
        SEARCH: 'Rechercher entreprise par nom',
        CANCEL: 'Annuler',
        EDIT: 'Modifier entreprise',
        NAME_EMPTY: 'Nom de la société ne peut être vide',
        DEFAULT_LANG_EMPTY: 'langue Société par défaut devrait être choisi',
        TYPE_EMPTY: 'type Compnay devrait être choisi'
      },
      SITE: {
        MENU: 'site',
        SITE: 'Gestion du site',
        ADD: 'ajouter',
        EDIT: 'éditer',
        CANCEL: 'annuler',
        DELETE: 'effacer',
        NEW: 'nouveau site',
        SAVE: 'Enregistrer',
        NAME: 'nom',
        ADDRESS: 'adresse',
        SEARCH: 'Site recherche par nom',
        NAME_EMPTY: 'Nom du site ne peut être vide',
        ADDRESS_EMPTY: 'Adresse du site ne peut être vide'
      },
      LOCATION: {
        MENU: 'emplacement',
        LOCATION_MANAGEMENT: 'Gestion de Localisation',
        LOCATION: 'emplacement',
        ADD: 'ajouter',
        EDIT: 'éditer',
        CANCEL: 'annuler',
        DELETE: 'effacer',
        NEW: 'nouveau emplacement',
        SAVE: 'Enregistrer',
        SITE: 'site',
        NAME: 'nom',
        NAME_EMPTY: 'Nom de l\'emplacement ne peut pas être vide',
        SITE_NAME_EMPTY: 'Site doit être choisi',
        SEARCH: 'Emplacement recherche par nom'
      },
      POSITION: {
        MENU: 'position',
        POSITION: 'position',
        POSITION_MANAGEMENT: 'Gestion des postes',
        ADD: 'ajouter',
        EDIT: 'éditer',
        CANCEL: 'annuler',
        DELETE: 'effacer',
        NEW: 'nouveau position',
        SAVE: 'Enregistrer',
        SITE: 'site',
        LOCATION: 'emplacement',
        NAME: 'nom',
        SHELF: 'étagère',
        BIN: 'coffre',
        CUR_QTY: 'Quantité actuelle',
        MIN_QTY: 'La quantité minimum',
        MAX_QTY: 'Montant maximum',
        CRITICAL_QTY: 'Nombre Critique',
        NAME_EMPTY: 'nom de position ne peut être vide',
        SITE_EMPTY: 'Site doit être choisi',
        LOCATION_EMPTY: 'emplacement doit être choisi',
        ITEM_EMPTY: 'devrait être choisi ',
        SHELF_EMPTY: 'étagère peut pas être vide',
        BIN_EMPTY: 'Bin ne peut être vide',
        MIN_QTY_EMPTY: 'quantité minimale ne peut être vide',
        MAX_QTY_EMPTY: 'quantité Max ne peut être vide',
        MAX_GREATER: 'quantité maximale devrait être supérieure à la quantité minimale',
        CRITICAL_QTY_EMPTY: 'quantité critique ne peut être vide',
        CRITICAL_QTY_LESS: 'quantité critique doit être inférieure ou égale à la quantité Min',
        ITEM: 'produit',
        SEARCH: 'Emplacement recherche par nom'
      },
      STORAGE_HIERARCHY: {
        MENU: 'stockage',
        SUB_MENU: 'Stockage Hiérarchie',
        STORAGE_HIERARCHY: 'Stockage Hiérarchie'
      },
      USER: {
        USERS: 'utilisateur',
        USER: 'utilisateur Enregistrer',
        SAVE: 'Enregistrer',
        NAME: 'nom',
        LAST_NAME: 'nom de famille',
        PHONE: 'téléphone',
        CELL_PHONE: 'téléphone portable',
        EMAIL: 'email',
        PASSWORD: 'mot de passe',
        LANGUAGE: 'langue',
        EDIT: 'éditer',
        CANCEL: 'annuler',
        DELETE: 'effacer',
        ROLE: 'Rôle',
        NEW: 'Nouvel utilisateur',
        LIST: 'liste',
        EDITION: 'édition',
        SEARCH: 'Rechercher un utilisateur...',
        WELCOME: 'bienvenue',
        SETTINGS: 'paramètres',
        CONTACT_SUPPORT: 'contacter le support',
        LOG_OUT: 'se déconnecter',
        SIGN_IN: 'se connecter',
        SIGN_UP: 'signer',
        USERROLE: 'Utilisateur',
        ADMINROLE: 'Administrateur',
        NAME_EMPTY: 'nom d\'utilisateur ne peut être vide',
        EMAIL_EMPTY: 'e-mail de l\'utilisateur ne peut pas être vide',
        LANGUAGE_EMPTY: 'langue de l\'utilisateur doit être choisi',
        PASSWORD_EMPTY: 'Mot de passe ne peut être vide',
        PASSWORD_SHORT: 'Mot de passe est trop court, il doit contenir au moins huit caractères',
        CHECKBOX_ROLE: 'Est admin?'
      },
      REPORT: {
        GENERAL_REPORTING: 'Rapport général',
        RESTOCK_MANAGEMENT: {
          TITLE: 'Repeupler Rapport',
          NEEDED_QTY: 'Quantité Nécessaire Minimale'
        },
        TITLE: 'rapports',
        ISSUE: {
          NUMBER: 'Nombre de lieux',
          TITLE: 'Inscription Nouvelles',
          USER_EMAIL: 'utilisateur',
          USER_NAME: 'nom',
          ITEM: 'Point Prise',
          ITEM_SKU: 'SKU nombre',
          QUANTITY: 'quantité',
          SITE: 'Numéro du site',
          LOCATION: 'Localisation des sites',
          POSITION: 'Tablette/Position',
          DATE: 'Date de Nouvelles',
          FROM: 'Nouveau à partir de',
          TO: 'New Up',
          FIND: 'Recherche Nouvelles'
        },
        CHECKBOOK: {
          TITLE: 'Carnet de Chèque',
          EVENT_TYPE: 'Type D\'événement',
          EVENT_DATE: 'Date de L\'événement'
        },
        LACK: {
          TITLE: 'Le manque d\'utilisation',
          HIDE: 'cacher les détails',
          SHOW: 'afficher les détails',
          ID: 'Id',
          NAME: 'nom',
          NO_ITEMS: 'Il n\'y a pas de produits'
        },
        STATS_FOR_VELOCITY: {
          TITLE: 'Statistiques de vitesse',
          SKU_NUMBER: 'Sku nombre',
          RATE: 'Taux de vitesse (unités/jour)',
          FROM: 'à partir de',
          TO: 'à',
          LOCATION: 'emplacement'
        }
      },
      DASHBOARD:{
        SHOW_DETAILS: 'Montrer plus de détails',
        VELOCITY: {
          TITLE: 'Ce est la meilleure moyenne ce mois-ci'
        },
        RATE: '{{value}}/jour'
      },
      NO_RESULTS: 'Résultats introuvables',
      BACK: 'Retour au tableau de bord'
    });
  }]);
}());
