window.angular.module('UIApp')
.config(['$translateProvider', function( $translateProvider ) {

  $translateProvider.translations('it', {
    GREETING: 'Ciao Mondo!',
    LANGUAGE: 'Lingua',
    ENGLISH: 'Inglese',
    SPANISH: 'Spagnolo',
    GERMAN: 'Tedesco',
    ITALIAN: 'Italiano',
    FRENCH: 'Francese',
    SEARCH: 'Ricerca',
    INCREASE: 'Aumentare',
    OLD_PASSWORD: 'Old Password',
    BUILD_SETUP: 'BUILD YOUR PRODUCT SETUP',
    PREVIOUS: 'Previous',
    FINISH: 'Finish',
    NEXT: 'Next',
    WIZARD_GUIDE: 'This wizard will take you throught product configuration.',
    CONFIRM_PASSWORD: 'Confirm new Password',
    SELECT_CSV: 'Import CSV',
    PASSWORD: 'Password',
    DECREASE: 'Diminuire',
    FROM: 'From',
    TO: 'To',
    EDIT: 'Edit',
    DELETE: 'Delete',
    CLEAN: 'Clean',
    ITEM_TO_ISSUE: 'Elemento di fornire',
    // LOCATION: 'Ubicación',
    // POSITION: 'Posición',
    PRODUCT: 'Prodotto/SKU',
    PRODUCT_SETUP: 'Impostazione Prodotto',
    PRODUCT_WIZARD: 'Procedura Guidata di Prodotto',
    ITEMS: 'Produtti',
    ITEM: 'Prodotto',
    QUANTITY: 'Quantità',
    INVENTORY_MANAGEMENT: 'Gestione delle scorte',
    MANUAL: 'Manuale',
    HELP: 'Aiuto',
    ABOUT: 'Su',
    STATUS: {
      ACTIVE: 'Attivo',
      INACTIVE: 'Inattivo',
      DISABLED: 'Disabilitato',
      PENDING: 'In attesa'
    },
    ACTIONS: {
      NEW: 'Nuovo',
      SEND: 'Inviare',
      REMOVE: 'Rimuovi',
      CANCEL: 'Annula',
      UPDATE: 'Aggiornamento',
      SEARCH: 'Ricerca',
      SERIALIZE: 'Creare unità serializzato'
    },
    PRODUCTS: {
      NEW_PRODUCT: 'Nuovo prodotto',
      PROPERTIES: 'Proprietà',
      NEW: 'Nuovo',
      PRODUCT: 'Prodotto',
      CANCEL: 'Annulla',
      SEND: 'Send',
      DESTROY: 'Distruggere',
      UPDATE: 'Aggiornamento',
      EDIT_PROD: 'Modificare prodotto',
      QRCODE: 'QR code',
      BARCODE: 'Codice a barre',
      SKU: 'SKU',
      SHORT_DESC: 'Breve descrizione',
      LONG_DESC: 'Descrizione lunga',
      ALT_DESC: 'Descrizione alternativa',
      FACT_NUM: 'Il numero di fabbrica',
      CUST_NUM: 'Numero del cliente',
      ALT_NUM: 'Numero Alternativa',
      SEC_ALT_NUM: 'Numero alternativa secondaria',
      MANUFACTURE: 'Produzione',
      CROSS_NUM: 'Numero Cross',
      SUPPLIER: 'Fornitore',
      SUPP_NUM: 'Il numero del fornitore',
      PRICE: 'Prezzo',
      CATEGORY: 'Categoria',
      COLOR: 'Colore',
      SERIAL: 'Serial',
      COMP_SIZE: 'Dimensioni del Scomparto',
      DIMENSIONS: 'Dimensioni',
      STATUS: 'Stato',
      EMPTY: 'Non cè prodotti',
      HELP_SHORT_DESC: 'Breve descrizione di questo prodotto',
      HELP_LONG_DESC: 'Descrizione lunga per questo prodotto',
      HELP_ALT_DESC: 'Descrizione di questo prodotto alternativo',
      TO_RESTOCK: 'Posizioni a rifornire',
      SKU_EMPTY: 'Sku non può essere vuoto',
      BARCODE_EMPTY: 'codice a barre non può essere vuoto',
      SHORT_DESC_EMPTY: 'Prodotto descrizione breve non può essere vuoto',
      DELETE_FAIL: 'Il prodotto non può essere cancellato'
    },
    INVENTORY: {
      ISSUE: 'Problema',
      RESTOCK: 'Rifornire',
      RECLAIM: 'Riprendiamoci',
      ASSIGN: 'Assegna',
      MOVE: {
        MOVE: 'Move',
        CAN_NOT_EMPTY_POS: "You can't choose an empty position!",
        CAN_EMPTY_POS: "You should choose an empty position!"
      },
      TRANSFER: 'Transfer',
      ENTER_PRODUCT: 'Inserire Prodotto Codice',
      FINISH_TRANSACTION: 'Fine transazione',
      REMOVE: 'Rimuovere',
      DEST_SITE: 'Destination site'
    },
    ASSETS: {
      TITLE: 'Titolo',
      EMPTY: 'Non cè attivi',
      NEW_ASSET: 'Nuovo bene',
      EDIT_ASSET: 'Editing bene',
      PRODUCT: 'Prodotto',
      CHECK_IN: 'Check in',
      CHECK_OUT: 'Check out',
      LOAN_TIME: 'Loan time (min)',
      LOAN_TIME_H: 'Loan time (ore)',
      RECHARGEAGLE: 'Ricaricabile',
      RECHARGEAGLE_TIME: 'Tempo ricaricabile (min)',
      CALIBRATION: 'Calibrazione',
      CALIBRATION_TIME: 'Periodo di tempo di calibrazione (min)',
      LOCKED_DOWN: 'Bloccato',
      REASON: 'Motivo',
      STATUS: 'Stato',
      ITEM_EMPTY: 'Prodotto non può essere vuoto',
      CALIBRATION_TIME_EMPTY: 'Periodo di tempo di calibrazione non può essere vuoto',
      RECHARGEABLE_TIME_EMPTY: 'Tempo ricaricabile non può essere vuoto '
    },
    COMPANY: {
      MENU: 'Società',
      COMPANY: 'Società di gestione',
      ADD: 'Aggiungi',
      DELETE: 'Elimina azienda',
      SAVE: 'Salvare',
      COMPANY_NAME: 'Nome Della Ditta',
      LOGO: 'Logo',
      MESSAGE: 'Messaggio',
      DEFAULT_LANG: 'lingua predefinita',
      ADDRESS: 'Indirizzo',
      COMPANY_TYPE: 'Tipo di societa',
      PHONE: 'Telefono',
      LOGGING: 'Registrazione',
      SEARCH: 'Cerca azienda per nome',
      CANCEL: 'Cancellare',
      EDIT: 'Modifica azienda',
      NAME_EMPTY: 'Firmenname darf nicht leer sein',
      DEFAULT_LANG_EMPTY: 'sollten Unternehmen Standardsprache ausgewählt werden',
      TYPE_EMPTY: 'Compnay Typ ausgewählt werden sollte'
    },
    SITE: {
      MENU: 'Luogo',
      SITE: 'Gestione del luogo',
      ADD: 'Aggiungi',
      EDIT: 'modifica',
      CANCEL: 'Annulla',
      DELETE: 'Elimina',
      NEW: 'nuovo sito',
      SAVE: 'Salvare',
      NAME: 'Nome',
      ADDRESS: 'Indirizzo',
      SEARCH: 'navigare sul sito per nome',
      NAME_EMPTY: 'Nome del sito non può essere vuoto',
      ADDRESS_EMPTY: 'Indirizzo del sito non può essere vuoto'
    },
    LOCATION: {
      MENU: 'Posizione',
      LOCATION_MANAGEMENT: 'Gestione della posizione',
      LOCATION: 'Posizione',
      ADD: 'Aggiungi',
      EDIT: 'modifica',
      CANCEL: 'Annulla',
      DELETE: 'Elimina',
      NEW: 'nuovo Posizione',
      SAVE: 'Salvare',
      SITE: 'Luogo',
      NAME: 'Nome',
      NAME_EMPTY: 'Nome posizione non può essere vuoto',
      SITE_NAME_EMPTY: 'Dovrebbe essere selezionato Site',
      SEARCH: 'navigare sul posizione per nome'
    },
    POSITION: {
      MENU: 'Posizione',
      POSITION: 'Posizione',
      POSITION_MANAGEMENT: 'Gestione della posizione',
      ADD: 'Aggiungi',
      EDIT: 'modifica',
      CANCEL: 'Annulla',
      DELETE: 'Elimina',
      NEW: 'nuovo Posizione',
      SAVE: 'Salvare',
      SITE: 'Luogo',
      LOCATION: 'Posizione',
      NAME: 'Nome',
      SHELF: 'Mensola',
      BIN: 'Scomparto',
      CUR_QTY: 'Quantità Corrente',
      MIN_QTY: 'Quantità minima',
      MAX_QTY: 'Importo Massimo',
      CRITICAL_QTY: 'Numero Critica',
      NAME_EMPTY: 'nome posizione non può essere vuoto',
      SITE_EMPTY: 'Sito deve essere selezionato',
      LOCATION_EMPTY: 'Luogo deve essere selezionato',
      ITEM_EMPTY: 'Articolo deve essere selezionato',
      SHELF_EMPTY: 'Shelf non può essere vuoto',
      BIN_EMPTY: 'Bin non può essere vuoto',
      MIN_QTY_EMPTY: 'la quantità minima non può essere vuoto',
      MAX_QTY_EMPTY: 'la quantità massima non può essere vuoto',
      MAX_GREATER: 'quantitativo massimo deve essere maggiore di quantità minima',
      CRITICAL_QTY_EMPTY: 'quantità critica non può essere vuoto',
      CRITICAL_QTY_LESS: 'quantità critica deve essere inferiore o uguale quantità minima',
      ITEM: 'Prodotto',
      SEARCH: 'navigare sul posizione per nome'
    },
    STORAGE_HIERARCHY: {
      MENU: 'Bagagli',
      SUB_MENU: 'Gerarchia di bagagli',
      STORAGE_HIERARCHY: 'Gerarchia di bagagli'
    },
    USER: {
      USERS: 'Utenti',
      USER: 'Registrazione utente',
      SAVE: 'Salvare',
      NAME: 'Nome',
      LAST_NAME: 'Cognome',
      PHONE: 'Telefono',
      CELL_PHONE: 'Telefono cellulare',
      EMAIL: 'E-mail',
      PASSWORD: 'Password',
      LANGUAGE: 'Lingua',
      EDIT: 'Modifica',
      CANCEL: 'Annulla',
      DELETE: 'Rimuovere',
      ROLE: 'Ruolo',
      NEW: 'Nuovo utente',
      LIST: 'Lista',
      EDITION: 'Edizione',
      SEARCH: 'Cerca utenter...',
      WELCOME: 'Benvenuto',
      SETTINGS: 'Impostazioni',
      CONTACT_SUPPORT: 'Contatta Il Supporto',
      LOG_OUT: 'Esci',
      SIGN_IN: 'Entra',
      SIGN_UP: 'Iscriviti',
      USERROLE: 'Utente',
      ADMINROLE: 'Amministratore',
      NAME_EMPTY: 'Nome utente non può essere vuoto',
      EMAIL_EMPTY: 'e-mail Utente non può essere vuoto',
      LANGUAGE_EMPTY: 'Lingua utente deve essere selezionato',
      PASSWORD_EMPTY: 'La password non può essere vuoto',
      PASSWORD_SHORT: 'password è troppo breve, dovrebbe contenere almeno otto caratteri',
      CHECKBOX_ROLE: 'È admin?'
    },
    REPORT: {
      GENERAL_REPORTING: 'Relazione generale',
      RESTOCK_MANAGEMENT: {
        TITLE: 'Fornitura Relazione',
        NEEDED_QTY: 'Minima Quantità Necessaria'
      },
      TITLE: 'Rapporti',
      ISSUE: {
        NUMBER: 'Problema',
        TITLE: 'Record Problema',
        USER_EMAIL: 'Utente',
        USER_NAME: 'Nome',
        ITEM: 'Articolo tratto',
        ITEM_SKU: 'Numero SKU',
        QUANTITY: 'Quantità',
        SITE: 'Sitio del Problema',
        LOCATION: 'Ubicación del Problema',
        POSITION: 'Mensola/Scomparto',
        DATE: 'Data di Emissione',
        FROM: 'Problemi di',
        TO: 'Problematica',
        FIND: 'Ricerca problemi'
      },
      CHECKBOOK: {
        TITLE: 'Checkbook',
        EVENT_TYPE: 'Tipo di Evento',
        EVENT_DATE: 'Evento Data'
      },
      LACK: {
        TITLE: 'La mancanza di utilizzo',
        HIDE: 'Nascondi dettagli',
        SHOW: 'Mostra dettagli',
        ID: 'Id',
        NAME: 'Nome',
        NO_ITEMS: 'Non ci sono prodotti'
      },
      STATS_FOR_VELOCITY: {
        TITLE: 'statistiche di velocità',
        SKU_NUMBER: 'Sku numero',
        RATE: 'tasso di velocità (unità/giorno)',
        FROM: 'da',
        TO: 'a',
        LOCATION: 'posizione'
      }
    },
    DASHBOARD:{
      SHOW_DETAILS: 'Mostra più dettagli',
      VELOCITY: {
        TITLE: "E 'la media migliore di questo mese"
      },
      RATE: '{{value}}/giorno'
    },
    NO_RESULTS: 'Non Risultati Trovati',
    BACK: 'Torna alla dashboard'
  });
}]);
